### ISSUE TITLE
Shift registers

### ISSUE THREAD

**Issue by selahattinerdal** [Am0k-GIT/STM32F401CCU6_UNI#1]
Hello, thanks for your work. Is it possible add shift registers for output pins and freeup some gpios?

**Comment by Am0k-GIT** [comment]
Hello, thank you for your interest in this project. There is a problem with adding shift registers: the board is universal (Marlin + GRBL), and all ports connected to peripherals must be protected. I believe that in order to increase the potential of the board, it is necessary to choose a controller with a large number of IOs. Possibly `STM32F401RC`.
